import type { TechNode } from './types';

export const TECH_TREE: Record<string, TechNode> = {
  efficientSolarPanels: {
    id: 'efficientSolarPanels',
    name: '高效太阳能板',
    description: '总发电量提升20%',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'powerBonus', value: 0.2 },
  },
  geneticallyEnhancedCrops: {
    id: 'geneticallyEnhancedCrops',
    name: '基因强化农作物',
    description: '农场产出提升30%',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'farmBonus', value: 0.3 },
  },
  nanoRepairBots: {
    id: 'nanoRepairBots',
    name: '纳米修复机器人',
    description: '每回合自动修复所有模块耐久+2',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'autoRepair', value: 2 },
  },
  efficientOxygenCycler: {
    id: 'efficientOxygenCycler',
    name: '高效氧气循环器',
    description: '生命维持模块氧气产出提升30%',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'oxygenBonus', value: 0.3 },
  },
  precisionManufacturing: {
    id: 'precisionManufacturing',
    name: '精密制造工艺',
    description: '工厂模块零件产出提升40%',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'factoryEfficiency', value: 0.4 },
  },
  distillationPurification: {
    id: 'distillationPurification',
    name: '蒸馏净化系统',
    description: '水循环回收率额外+20%',
    cost: 50,
    tier: 1,
    prerequisites: [],
    researched: false,
    effect: { type: 'waterRecoveryBonus', value: 0.2 },
  },

  cryoSleepChambers: {
    id: 'cryoSleepChambers',
    name: '冷冻休眠舱',
    description: '可冻结部分人口减少资源消耗',
    cost: 100,
    tier: 2,
    prerequisites: ['geneticallyEnhancedCrops'],
    researched: false,
    effect: { type: 'cryoChambers', value: 0 },
  },
  shieldUpgrade: {
    id: 'shieldUpgrade',
    name: '护盾升级',
    description: '陨石伤害减免50%',
    cost: 100,
    tier: 2,
    prerequisites: ['efficientSolarPanels'],
    researched: false,
    effect: { type: 'shieldUpgrade', value: 0.5 },
  },
  aiPiloting: {
    id: 'aiPiloting',
    name: 'AI辅助驾驶',
    description: '引擎效率提升25%',
    cost: 100,
    tier: 2,
    prerequisites: ['nanoRepairBots'],
    researched: false,
    effect: { type: 'engineEfficiency', value: 0.25 },
  },
  nanoMedicalBots: {
    id: 'nanoMedicalBots',
    name: '纳米医疗机器人',
    description: '医疗舱治疗效率提升50%',
    cost: 100,
    tier: 2,
    prerequisites: ['efficientOxygenCycler'],
    researched: false,
    effect: { type: 'medicalEfficiency', value: 0.5 },
  },
  psychologicalCounseling: {
    id: 'psychologicalCounseling',
    name: '心理疏导系统',
    description: '全员每回合士气额外+2',
    cost: 100,
    tier: 2,
    prerequisites: ['distillationPurification'],
    researched: false,
    effect: { type: 'moraleBonus', value: 2 },
  },
  reinforcedArmor: {
    id: 'reinforcedArmor',
    name: '强化装甲设计',
    description: '防御系统拦截效果提升50%',
    cost: 100,
    tier: 2,
    prerequisites: ['precisionManufacturing'],
    researched: false,
    effect: { type: 'defenseEfficiency', value: 0.5 },
  },

  warpPrototype: {
    id: 'warpPrototype',
    name: '曲速原型机',
    description: '航行速度翻倍但有故障风险',
    cost: 200,
    tier: 3,
    prerequisites: ['cryoSleepChambers', 'shieldUpgrade', 'aiPiloting'],
    researched: false,
    effect: { type: 'warpDrive', value: 2 },
  },
  metalMolecularReconstruction: {
    id: 'metalMolecularReconstruction',
    name: '金属分子重组',
    description: '每回合自动再生15单位金属',
    cost: 200,
    tier: 3,
    prerequisites: ['reinforcedArmor', 'nanoMedicalBots'],
    researched: false,
    effect: { type: 'metalRegeneration', value: 15 },
  },
  bioCycleReactor: {
    id: 'bioCycleReactor',
    name: '生物循环反应堆',
    description: '每回合将50%废物转化为等量食物',
    cost: 200,
    tier: 3,
    prerequisites: ['psychologicalCounseling', 'nanoMedicalBots'],
    researched: false,
    effect: { type: 'wasteRecycling', value: 0.5 },
  },
};
